name: mad_pay_android
description: A plug-in to add support for payments on the Android side of Mad Pay
version: 2.2.0
repository: https://github.com/MadBrains/Mad-Pay-Flutter
issue_tracker: https://github.com/MadBrains/Mad-Pay-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mad_pay_platform_interface: ^2.2.0
  flutter_svg: ^0.22.0

# For development. Remove/comment before publishing to pub.
# dependency_overrides:
#   mad_pay_platform_interface:
#     path: ../mad_pay_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/en/
    - assets/ar/
    - assets/bg/
    - assets/ca/
    - assets/cs/
    - assets/da/
    - assets/de/
    - assets/el/
    - assets/es/
    - assets/et/
    - assets/fi/
    - assets/fr/
    - assets/hr/
    - assets/id/
    - assets/it/
    - assets/ja/
    - assets/ko/
    - assets/ms/
    - assets/nl/
    - assets/no/
    - assets/pl/
    - assets/pt/
    - assets/ru/
    - assets/sk/
    - assets/sl/
    - assets/sr/
    - assets/sv/
    - assets/th/
    - assets/tr/
    - assets/uk/
    - assets/zh/

  plugin:
    platforms:
      android:
        package: ru.madbrains.mad_pay_android
        pluginClass: MadPayAndroidPlugin