name: mad_pay_example
description: Demonstrates how to use the mad_pay plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0-0 <3.0.0"
  flutter: ">=2.11.0-0.1.pre"

dependencies:
  flutter:
    sdk: flutter

  mad_pay:
    path: ../packages/mad_pay

# For development. Remove/comment before publishing to pub.
# dependency_overrides:
#   mad_pay:
#     path: ../packages/mad_pay
#   mad_pay_platform_interface:
#     path: ../packages/mad_pay_platform_interface
#   mad_pay_android:
#     path: ../packages/mad_pay_android
#   mad_pay_ios:
#     path: ../packages/mad_pay_ios

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true