version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/packages/mad_pay/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/mad_pay_android/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/mad_pay_ios/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/mad_pay_platform_interface/"
    schedule:
      interval: "weekly"
