name: mad_pay

packages:
  - packages/**
  - example/*

ide:
  intellij:
    true
  vscode:
    true

scripts:
  postclean: >
    melos exec -c 1 -- "flutter clean"

  format: >
    melos exec -c 6 --ignore="*example*" -- \
      dartfmt -w .

  analyze:
    run: |
      melos exec -c 1 --no-private --ignore="*example*" -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  lint:pub: >
    melos exec -c 1 --fail-fast --no-private --ignore="*example*" -- \
      pub publish --dry-run

  lint:pana: >
    melos exec -c 1 --fail-fast --no-private --ignore="*example*" -- \
      pana

  proto: >
    ./tool/gen.sh && melos run format
