name: mad_pay
description: Mad Pay will help you make payments through Apple Pay and Google Pay
version: 2.2.14
repository: https://github.com/MadBrains/Mad-Pay-Flutter
issue_tracker: https://github.com/MadBrains/Mad-Pay-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

  mad_pay_platform_interface: ^2.2.14
  mad_pay_android: ^2.2.14
  mad_pay_ios: ^2.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: mad_pay_android
      ios:
        default_package: mad_pay_ios