name: mad_pay
description: Mad Pay will help you make payments through Apple Pay and Google Pay
version: 2.2.9
repository: https://github.com/MadBrains/Mad-Pay-Flutter
issue_tracker: https://github.com/MadBrains/Mad-Pay-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  mad_pay_platform_interface: ^2.2.3
  mad_pay_android: ^2.2.8
  mad_pay_ios: ^2.2.5

# For development. Remove/comment before publishing to pub.
# dependency_overrides:
#   mad_pay_platform_interface:
#     path: ../mad_pay_platform_interface
#   mad_pay_android:
#     path: ../mad_pay_android
#   mad_pay_ios:
#     path: ../mad_pay_ios

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: mad_pay_android
      ios:
        default_package: mad_pay_ios