name: pull_request

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
      - name: 'Install Dart'
        uses: dart-lang/setup-dart@v1.3
      - name: 'Install Tools'
        run: dart pub global activate pana; dart pub global activate fvm; make init; ln -sf bash /bin/sh;
      - name: 'Pana'
        run: make pana
          
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
      - name: 'Install Dart'
        uses: dart-lang/setup-dart@v1.3
      - name: 'Install Tools'
        run: dart pub global activate fvm; make init;
      - name: 'Format Code'
        run: make fix
      - name: 'Validate Formatting'
        run: ./tool/validate-formatting.sh